version: "3"

services:
  mysql:
    container_name: mysql-api-compose
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=securePassword
      - MYSQL_DATABASE=dbDev
    volumes:
      - ${HOME}/Downloads/DockerVolumes/mysql/api_leo:/var/lib/mysql