version: "3"

services:
  mysql:
    container_name: mysql-api-compose
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=securePassword
      - MYSQL_DATABASE=dbDev
    volumes:
      - ${HOME}/Downloads/DockerVolumes/mysql/api_leo:/var/lib/mysql
  prometheus:
    image: prom/prometheus
    container_name: prometheus-compose
    ports:
      - "9090:9090"
    volumes:
      - /${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana-compose
    ports:
      - '3000:3000'
    volumes:
      - ${HOME}/Downloads/DockerVolumes/grafana/:/var/lib/grafana
    restart: always
    user: 0:0