server:
  port: 8383

spring:
  application:
    name: api-leo
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbDev?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: securePassword
  jpa:
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  main:
    banner-mode: off

logging:
  level:
    org.springframework.boot.flyway: WARN
    org.springframework.boot.sql: WARN
    org.springframework.boot.web: WARN

debug: false
