server:
  port: 8383

spring:
  application:
    name: api-leo
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://198.168.0.50:3308/dbDev?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: securePassword
  jpa:
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    open-in-view: off
    hibernate:
      ddl-auto: none
  main:
    banner-mode: off
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
        exclude: "loggers, env"
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        request:
          autotime:
            percentiles-histogram: true
            percentiles: 0.5, 0.75, 0.9
      client:
        request:
          autotime:
            percentiles-histogram: true
            percentiles: 0.5, 0.75, 0.9

logging:
  level:
    org.springframework.boot.sql: WARN
    org.springframework.boot.web: WARN

debug: false
